# GENERATED by `hangar colours sync` (~/code/dvb_gn) -- do not edit by hand.
# Canonical per-clone hues for the dvb_gn hangar. Sourceable by sh/bash/zsh.
# The hues are data in src/palette.ts and everything else is derived from them;
# editing this file instead just means the next sync silently reverts you.
#
# hangar_dvb_gn_colour <clone_NN>  ->  "<r;g;b> <xterm-256 index> <name>"
#
# Read it with two lines, in any POSIX shell:
#     set -- $(hangar_dvb_gn_colour "$clone") ; rgb=$1 x256=$2 name=$3
#
# One other place cannot source this file and carries its own copy of the table:
#   ~/.claude/dvb-clone-statusline.sh   (self-contained on purpose: it runs on every
#                                        status-line render and must never fail)
# It is generated from the same data, so the two cannot drift.
#
# Formula, so the set reads as one family: shimmer = main + 40% toward white,
# border = main x 0.8, statusline dim = main x 0.6.

hangar_dvb_gn_colour() {
    case "$1" in
        clone_01) printf '0;204;255 45 cyan'    ;;   # #00ccff
        clone_02) printf '255;204;0 220 yellow' ;;   # #ffcc00
        clone_03) printf '0;204;0 40 green'     ;;   # #00cc00
        clone_04) printf '255;68;68 203 red'    ;;   # #ff4444
        *)        return 1 ;;
    esac
}
