#!/usr/bin/env bash
# Status line for a session at the HANGAR ROOT -- ops mode, dev mode, or no mode at all.
#
# Hand-maintained, unlike ~/.claude/<id>-clone-statusline.sh, which looks like the obvious
# precedent and is the wrong model in two ways: that one is GENERATED by `hangar colours sync`
# (so it may hardcode the fleet root) and it derives a CLONE from the payload's directory. This
# one belongs to the modes beside it, is tracked, and resolves the hangar root from its own
# location -- the rule bin/hangar and bin/hangar-mode both follow.
#
# WHICH MODE, from three independent channels, because none of the three can be verified from
# outside an interactive session:
#   1. $1                 -- passed by .claude/modes/<mode>.settings.json, which reaches the
#                            session as `claude --settings`. Authoritative when it arrives.
#   2. $HANGAR_MODE       -- exported by bin/hangar-mode. Covers the case where the root
#                            .claude/settings.json's argv-less entry is the one that won.
#   3. neither            -- a red NO MODE badge.
# So the three open questions -- whether --settings carries non-permission keys, whether it
# outranks project settings, and whether this subprocess inherits the environment -- do not need
# answering: any one channel working shows the right badge, and all three failing shows a red
# warning rather than a confident wrong one. Do not "simplify" this to one channel.
#
# $HANGAR_MODE is exported ONLY by bin/hangar-mode. It must never be set from .envrc or
# .envrc.hangar: the moment direnv exports it, every shell in the hangar carries it and the
# NO MODE badge stops meaning anything.
#
# Never fails, by contract -- it runs on every render: no sourcing of files that may be missing,
# and jq is optional (without it the badge still renders, which is the part that matters).
#
# So the body is PLAIN POSIX, even though the shebang is bash and bash is what normally runs it:
# a contract that says "never fails" has to hold when something else does. Three bashisms were
# tried and all three break a POSIX shell -- `set -o pipefail` aborts it outright ("Illegal
# option"), `${BASH_SOURCE[0]}` is a Bad substitution (and is unset in zsh, where it silently
# yielded the wrong directory), and `$'\033'` comes out as a literal `$[`. None of the three is
# needed: nothing here depends on pipefail, $0 is the script path for every invocation but a
# `source` (not a real status-line path), and ESC is one printf.
set -u

mode="${1:-${HANGAR_MODE:-}}"

# An explicit background, never \033[7m: reverse video inverts against each window's own theme,
# so the badge would change colour per terminal -- the exact ambiguity this removes. White bold
# on a solid ground reads the same everywhere, and the WORD survives a terminal that drops the
# colour entirely.
case "$mode" in
    ops) badge=" OPS "; bg="31;111;235" ;;      # cool blue  -- you read and run
    dev) badge=" DEV "; bg="179;84;0" ;;        # warm amber -- you change things
    *)   badge=" NO MODE "; bg="204;0;0" ;;     # red -- launched bare, or resumed without its mode
esac

hangar="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd -P)" || hangar=""

# A search list, not one literal. A status line is spawned by Claude Code rather than by the
# developer's shell, so jq is easily off PATH on a machine where typing `jq` works -- and the old
# fallback `/opt/homebrew/bin/jq` is Homebrew on Apple Silicon and nowhere else. When it misses,
# `field()` returns empty for everything and the badge renders blank rather than erroring.
# The IDENTICAL list is generated by app/src/generate/statusline-sh.ts for the clone status line;
# nothing derives this file from it, so change one and change both.
JQ="$(command -v jq || true)"
if [ -z "$JQ" ]; then
    for candidate in /opt/homebrew/bin/jq /usr/local/bin/jq /usr/bin/jq /bin/jq \
                     /snap/bin/jq "$HOME/.local/bin/jq"; do
        if [ -x "$candidate" ]; then JQ="$candidate"; break; fi
    done
fi

input="$(cat)"
field() {
    [ -x "$JQ" ] || return 0
    printf '%s' "$input" | "$JQ" -r "$1 // empty" 2>/dev/null
}

dir="$(field '.workspace.current_dir')"
[ -n "$dir" ] || dir="$PWD"
model="$(field '.model.display_name')"

# The hangar's own name, plus where in it this session is standing -- `dvb_gn` for ops,
# `dvb_gn/app` for dev, since that is dev mode's working directory and how app/CLAUDE.md
# reaches it on turn one. Named rather than assumed: Hangar's premise is several hangars on
# one machine, and two root windows are the new instance of the failure the clone colours fix.
where=""
if [ -n "$hangar" ]; then
    where="$(basename "$hangar")"
    case "$dir" in
        "$hangar") ;;
        "$hangar"/*) where="${where}/${dir#"$hangar"/}" ;;
        *) where="$(basename "$dir")" ;;   # somewhere else entirely; say so rather than lie
    esac
else
    where="$(basename "$dir")"
fi

esc="$(printf '\033')"
b="${esc}[1;38;2;255;255;255;48;2;${bg}m"   # badge: white bold on the mode's ground
d="${esc}[38;2;120;120;120m"                # separators and secondary text
r="${esc}[0m"

out="${b}${badge}${r} ${where}"
[ -n "$model" ] && out="${out}${d} · ${model}${r}"
printf '%s' "$out"
