#!/bin/sh
# GENERATED by `hangar colours sync` (%HANGAR%) -- do not edit by hand.
# one field of the clone status bar: clone-tmux-status.sh <footer|ticket|pr> <clone> [path]
# Called by the `#()` jobs in clone-tmux.conf, once per field per status refresh.
# Every failure is a silent exit 0: a status bar is no place for an error message.

set -u

ROOT='%HANGAR%'
PR_DIR='%HANGAR%/.hangar/pr'
KEY_PATTERN='^(UI|PLAT)-[0-9]+'
DEFAULT_BRANCH='release'
HANGAR='%HANGAR%/bin/hangar'
PR_TTL=45
PR_LOCK_STALE=300
BRANCH_MAX=72
PATH_MAX=36

field=${1:-}
clone=${2:-}
pane_path=${3:-}

# No clone means the session carries no @hangar_clone -- one somebody made by hand on this
# socket. It is on the same bar, and it is not a clone, so there is nothing to say about it.
[ -n "$field" ] || exit 0
[ -n "$clone" ] || exit 0
dir="$ROOT/$clone"
[ -d "$dir" ] || exit 0

# `symbolic-ref` and not `branch --show-current`: one ref read rather than a branch walk,
# and it exits non-zero on a detached HEAD, which is the answer "no branch" anyway. The
# footer asks git for its own branch, since one `status -b` answers that and three more.
branch=$(git -C "$dir" symbolic-ref --quiet --short HEAD 2>/dev/null) || branch=""

case "$field" in
footer)
  # Where in the clone this pane is standing. tmux knows the path and hands it over, so
  # nothing here has to guess -- and a pane that has wandered outside the clone says so
  # rather than pretending, because a footer naming the wrong tree is worse than a long one.
  rel=""
  case "$pane_path" in
  "$dir") ;;
  "$dir"/*) rel=${pane_path#"$dir"/} ;;
  "$HOME"/*) rel="~/${pane_path#"$HOME"/}" ;;
  ?*) rel=$pane_path ;;
  esac
  # From the END: the leaf directory is what says where you are, and the segments in front
  # of it are the ones the clone name has already implied.
  if [ ${#rel} -gt "$PATH_MAX" ]; then
    rel="…$(printf '%s' "$rel" | cut -c$((${#rel} - PATH_MAX + 2))-)"
  fi

  # One walk for the branch, the ahead/behind counts and every file state. See the header
  # for why --no-optional-locks is load-bearing rather than tidy.
  staged="" modified="" untracked="" conflict="" ahead="" behind="" head=""
  status=$(git -C "$dir" --no-optional-locks status --porcelain=v1 -b 2>/dev/null) || status=""
  # A here-document, not a pipe: a `while read` on the right of a pipe runs in a subshell in
  # every POSIX shell, and each variable set below would be discarded at the `done`.
  while IFS= read -r line; do
    case "$line" in
    "## "*)
      head=${line#"## "}
      head=${head%%...*}
      case "$line" in *'[ahead '*) n=${line#*'[ahead '}; n=${n%%,*}; ahead=${n%%]*} ;; esac
      case "$line" in *'behind '*) n=${line#*'behind '}; behind=${n%%]*} ;; esac
      ;;
    "??"*) untracked=1 ;;
    # A `U` on either side, and the two both-added/both-deleted spellings that carry none.
    U?*|?U*|AA*|DD*) conflict=1 ;;
    # A leading space is an empty index column: changed in the tree and not staged.
    " "*) modified=1 ;;
    ?*)
      staged=1
      case "$line" in ?M*|?D*) modified=1 ;; esac
      ;;
    esac
  done <<EOF
$status
EOF

  # A branch called `something_behind_x` would otherwise be read as a count. Both counts come
  # from the same line as the branch name, so both are checked rather than trusted.
  case "$ahead" in "" | *[!0-9]*) ahead="" ;; esac
  case "$behind" in "" | *[!0-9]*) behind="" ;; esac

  # A rebase or a merge is the state worth interrupting a glance for, so it leads.
  git_dir=$(git -C "$dir" rev-parse --git-dir 2>/dev/null) || git_dir=""
  marks=""
  if [ -n "$git_dir" ]; then
    case "$git_dir" in /*) ;; *) git_dir="$dir/$git_dir" ;; esac
    if [ -d "$git_dir/rebase-merge" ] || [ -d "$git_dir/rebase-apply" ] ||
      [ -f "$git_dir/MERGE_HEAD" ]; then
      marks="${marks}⚑"
    fi
  fi
  [ -n "$conflict" ] && marks="${marks}‼"
  [ -n "$staged" ] && marks="${marks}✚"
  [ -n "$modified" ] && marks="${marks}✱"
  [ -n "$untracked" ] && marks="${marks}?"
  # Nothing to say IS the thing to say. An empty run of glyphs would read as a broken
  # script rather than as a clean tree, so a clean tree gets a character of its own -- and
  # it is decided BEFORE the arrows, because a tree that is clean and merely ahead of its
  # remote is clean, and a lone `⇡6` there reads as an answer with the first half missing.
  [ -n "$marks" ] || marks='✔'
  [ -n "$ahead" ] && marks="${marks}⇡${ahead}"
  [ -n "$behind" ] && marks="${marks}⇣${behind}"

  # `status -b` names the branch too, and answers on a detached HEAD where `symbolic-ref`
  # cannot -- there it prints `HEAD (no branch)`, which is the honest thing to show.
  [ -n "$branch" ] || branch=$head
  if [ ${#branch} -gt "$BRANCH_MAX" ]; then
    branch="$(printf '%s' "$branch" | cut -c1-"$BRANCH_MAX")…"
  fi

  out=" $clone"
  [ -n "$rel" ] && out="$out · $rel"
  out="$out · $marks"
  [ -n "$branch" ] && out="$out · $branch"
  printf '%s ' "$out"
  ;;
ticket)
  [ -n "$branch" ] || exit 0
  [ -n "$KEY_PATTERN" ] || exit 0
  # `tr` first, so the match runs on words: `_` and `/` are separators in a branch name but
  # word characters to grep, and `-` has to survive because it is inside the key.
  key=$(printf '%s' "$branch" | tr -cs 'A-Za-z0-9-' '\n' | grep -oE "$KEY_PATTERN" |
    head -1) || key=""
  [ -n "$key" ] || exit 0
  printf ' %s ' "$key"
  ;;
pr)
  [ -n "$branch" ] || exit 0
  # Nothing to say about the default branch: it has no pull request of its own, and a link
  # to "the pull requests for master" is a link to everything.
  [ "$branch" != "$DEFAULT_BRANCH" ] || exit 0

  # Everything below comes off DISK. Asking Bitbucket costs two round trips and about a
  # second, and this runs per attached client per interval -- see `pr-cache.ts`. A line
  # naming another branch is not this branch's pull request, so it is dropped rather than
  # shown: that is what keying the record on the branch is for.
  c_branch="" c_id="" c_at="" c_state="" c_draft="" c_ci="" c_review=""
  if [ -f "$PR_DIR/$clone" ]; then
    read -r c_branch c_id _c_url c_at c_state c_draft c_ci c_review _rest \
      <"$PR_DIR/$clone" || c_branch=""
  fi
  if [ "$c_branch" != "$branch" ]; then
    c_branch="" c_id="" c_at="" c_state="" c_draft="" c_ci="" c_review=""
  fi
  case "$c_at" in "" | *[!0-9]*) c_at=0 ;; esac

  # Past the TTL, hand the question to a detached `hangar pr refresh` and draw the OLD value
  # now. Nothing here ever waits for the network: the fresh answer lands at the next redraw.
  # This is also why a hangar nobody is looking at makes no requests -- the only thing that
  # starts a refresh is a pane being drawn.
  now=$(date +%s 2>/dev/null) || now=0
  if [ "$now" -gt 0 ] && [ "$((now - c_at))" -ge "$PR_TTL" ]; then
    lock="$PR_DIR/.lock-$clone"
    # A refresher that was killed leaves its lock behind, which would wedge this clone's
    # field for good. The epoch inside the lock is what lets the next redraw tell a run in
    # progress from a corpse.
    if [ -d "$lock" ]; then
      lock_at=$(cat "$lock/at" 2>/dev/null) || lock_at=0
      case "$lock_at" in "" | *[!0-9]*) lock_at=0 ;; esac
      [ "$((now - lock_at))" -ge "$PR_LOCK_STALE" ] && rm -rf "$lock"
    fi
    # `mkdir` is the atomic primitive: of every pane in every window drawing this field at
    # once, exactly one creates the directory, so exactly one refresher is spawned.
    mkdir -p "$PR_DIR" 2>/dev/null
    if mkdir "$lock" 2>/dev/null; then
      printf '%s' "$now" >"$lock/at" 2>/dev/null
      # Every descriptor is closed: tmux waits for a job's stdout to reach EOF, so a child
      # holding it open would hang the bar rather than the other way round.
      ("$HANGAR" pr refresh "$clone" >/dev/null 2>&1; rm -rf "$lock") \
        </dev/null >/dev/null 2>&1 &
    fi
  fi

  # Nothing known, or known to be nothing. Both draw the bare label: the click opens this
  # branch's pull requests, which is true either way, and a cold cache with nothing on the
  # bar would leave nothing to click.
  if [ -z "$c_branch" ] || [ "$c_id" = "0" ]; then
    printf ' PR '
    exit 0
  fi

  case "$c_state" in
  merged) printf ' ✔#%s ' "$c_id" ;;
  declined) printf ' ✖#%s ' "$c_id" ;;
  superseded) printf ' ⊘#%s ' "$c_id" ;;
  *)
    mark=""
    [ "$c_draft" = "1" ] && mark='✎'
    out=" $mark#$c_id"
    # Colour, which the FOOTER may never use -- the two lines of this bar sit on different
    # backgrounds. Down there it is the clone's hue with ink on it, where a red mark on the
    # red clone would be invisible; up here it is the one neutral the whole fleet shares, so
    # `palette.ts` can prove a floor against it. tmux expands `#[...]` out of a job's output
    # -- measured, not assumed -- which is what makes this reachable from a shell script.
    case "$c_ci" in
    pass) out="$out #[fg=#26a641]✓#[default]" ;;
    fail) out="$out #[fg=#f04343]✗#[default]" ;;
    running) out="$out #[fg=#d9a800]◌#[default]" ;;
    esac
    case "$c_review" in
    approved) out="$out +" ;;
    changes) out="$out ≈" ;;
    *) out="$out ·" ;;
    esac
    printf '%s ' "$out"
    ;;
  esac
  ;;
esac
