#!/bin/sh
# GENERATED by `hangar colours sync` (%HANGAR%) -- do not edit by hand.
# one field of the clone status bar: clone-tmux-status.sh <branch|ticket|pr> <clone>
# Called by the `#()` jobs in clone-tmux.conf, once per field per status refresh.
# Every failure is a silent exit 0: a status bar is no place for an error message.

set -u

ROOT='%HANGAR%'
PR_DIR='%HANGAR%/.hangar/pr'
KEY_PATTERN='^(UI|PLAT)-[0-9]+'
DEFAULT_BRANCH='release'
BRANCH_MAX=72

field=${1:-}
clone=${2:-}

# No clone means the session carries no @hangar_clone -- one somebody made by hand on this
# socket. It is on the same bar, and it is not a clone, so there is nothing to say about it.
[ -n "$field" ] || exit 0
[ -n "$clone" ] || exit 0
dir="$ROOT/$clone"
[ -d "$dir" ] || exit 0

# `symbolic-ref` and not `branch --show-current`: one ref read rather than a branch walk,
# and it exits non-zero on a detached HEAD, which is the answer "no branch" anyway.
branch=$(git -C "$dir" symbolic-ref --quiet --short HEAD 2>/dev/null) || branch=""
[ -n "$branch" ] || exit 0

case "$field" in
branch)
  if [ ${#branch} -gt "$BRANCH_MAX" ]; then
    printf ' %s… ' "$(printf '%s' "$branch" | cut -c1-"$BRANCH_MAX")"
  else
    printf ' %s ' "$branch"
  fi
  ;;
ticket)
  [ -n "$KEY_PATTERN" ] || exit 0
  # `tr` first, so the match runs on words: `_` and `/` are separators in a branch name but
  # word characters to grep, and `-` has to survive because it is inside the key.
  key=$(printf '%s' "$branch" | tr -cs 'A-Za-z0-9-' '\n' | grep -oE "$KEY_PATTERN" |
    head -1) || key=""
  [ -n "$key" ] || exit 0
  printf ' %s ' "$key"
  ;;
pr)
  # Nothing to say about the default branch: it has no pull request of its own, and a link
  # to "the pull requests for master" is a link to everything.
  [ "$branch" != "$DEFAULT_BRANCH" ] || exit 0
  # The number comes off disk because asking Bitbucket for it costs a token and up to eight
  # seconds -- see `pr-cache.ts`. A cache line for another branch is not this branch's pull
  # request, so it is ignored rather than shown: that is what keying it on the branch is for.
  if [ -f "$PR_DIR/$clone" ] &&
    read -r cached_branch cached_id _rest <"$PR_DIR/$clone" &&
    [ "$cached_branch" = "$branch" ] && [ -n "$cached_id" ]; then
    printf ' PR#%s ' "$cached_id"
  else
    # A label rather than a claim: the click opens this branch's pull requests, which is a
    # true statement whether or not one exists. Without it a cold cache would leave nothing
    # on the bar to click, and the number only ever arrives by someone asking once.
    printf ' PR '
  fi
  ;;
esac
