#!/usr/bin/env bash
# GENERATED by `hangar colours sync` (%HANGAR%) -- do not edit by hand.
# Status line for the vsfix hangar's clones (%HANGAR%/checkout_[0-9][0-9][0-9][0-9]*).
# The hues are data in src/palette.ts and everything else is derived from them;
# editing this file instead just means the next sync silently reverts you.
#
# ONE script for all clones: the colour is derived from the clone directory in the stdin
# payload, never from an argument, so every clone runs identical code and only the hue
# differs. Hues match ~/.claude/themes/vsfix-clone-*.json exactly, because both are
# generated from src/palette.ts.
set -uo pipefail

JQ="$(command -v jq || true)"
if [ -z "$JQ" ]; then
    for candidate in /opt/homebrew/bin/jq /usr/local/bin/jq /usr/bin/jq /bin/jq \
                     /snap/bin/jq "$HOME/.local/bin/jq"; do
        if [ -x "$candidate" ]; then JQ="$candidate"; break; fi
    done
fi

input="$(cat)"
field() { printf '%s' "$input" | "$JQ" -r "$1 // empty" 2>/dev/null; }

dir="$(field '.workspace.current_dir')"
[ -n "$dir" ] || dir="$PWD"

# The clone is the path segment under the hangar root, not basename($dir) -- a session
# started in a SUBDIRECTORY of a clone must still report the clone. The digit count is
# open at the top, so this keeps working past the first index that needs another digit.
FLEET='%HANGAR%'
clone="$(printf '%s' "$dir" | sed -n "s|^${FLEET}/\(checkout_[0-9][0-9][0-9][0-9]*\).*|\1|p")"
[ -n "$clone" ] || clone="$(basename "$dir")"

# Same triples as the theme files: main / dim.
case "$clone" in
    checkout_0001) main="0;204;255"; dim="0;122;153" ;;   # cyan
    checkout_0002) main="255;204;0"; dim="153;122;0" ;;   # yellow
    checkout_0003) main="0;204;0";   dim="0;122;0"   ;;   # green
    *)             main="150;150;150"; dim="100;100;100" ;;
esac

c()  { printf '\033[38;2;%sm' "$main"; }
d()  { printf '\033[38;2;%sm' "$dim"; }
r()  { printf '\033[0m'; }

model="$(field '.model.display_name')"
session="$(field '.session_id')"
used="$(field '.context_window.total_input_tokens')"
window="$(field '.context_window.context_window_size')"
pct="$(field '.context_window.used_percentage')"

# 232921 -> 233k, 1000000 -> 1M. Integer arithmetic only: `bc` is not a dependency this
# script is allowed to acquire, and awk for one rounding is a process per render.
# Anything that is not a run of digits prints nothing, which is how a payload without the
# field -- an older Claude Code, a shape that has moved -- costs a segment and never a line.
hum() {
    case "${1:-}" in "" | *[!0-9]*) return 0 ;; esac
    if [ "$1" -ge 1000000 ]; then
        local m=$(($1 / 1000000)) f=$((($1 % 1000000) / 100000))
        if [ "$f" -eq 0 ]; then printf '%dM' "$m"; else printf '%d.%dM' "$m" "$f"; fi
    elif [ "$1" -ge 1000 ]; then
        printf '%dk' "$((($1 + 500) / 1000))"
    else
        printf '%d' "$1"
    fi
}

# The clone is the coloured bullet and nothing else: its name, its path and its branch are
# on the tmux footer, in this clone's own hue, with room to spare. The bullet is what still
# names it in a session started outside hangar's tmux, where there is no footer at all.
out="$(c)$(printf '\033[1m')●$(r)"

# `233k/1M · 23%`: the percentage is what gets read, and the pair either side of it is what
# says whether 23 per cent is a lot. Claude Code's own badge shows the same first number raw
# and neither of the other two.
used_h="$(hum "$used")"
window_h="$(hum "$window")"
if [ -n "$used_h" ]; then
    out="${out} $(c)${used_h}$(r)"
    [ -n "$window_h" ] && out="${out}$(d)/${window_h}$(r)"
fi
case "${pct:-}" in
    "" | *[!0-9]*) ;;
    *) out="${out}$(d) · ${pct}%$(r)" ;;
esac
[ -n "$model" ] && out="${out}$(d) · ${model}$(r)"

# The first eight characters of the session id, which is enough to tell two sessions in one
# clone apart and is the handle `claude --resume` takes -- so the thing that brings this
# conversation back is on screen rather than dug out of a transcript directory.
[ -n "$session" ] && out="${out}$(d) · ${session:0:8}$(r)"
printf '%s' "$out"
