/**
 * The conventional-changelog preset used to write CHANGELOG.md, run by `pnpm changelog`.
 *
 * **Its type list is not written here.** It is read out of the root `.releaserc.json`, which is
 * where semantic-release reads the same list from in CI. Two copies of an eleven-entry table that
 * MUST agree is exactly the drift this repo keeps finding: the sections generated by hand and the
 * sections semantic-release later prepends to the same file would end up with different titles,
 * and nothing would say so. One source, read twice.
 *
 * The list exists at all because the `conventionalcommits` preset hides everything but `feat`,
 * `fix` and `perf` by default, and for this history that is wrong rather than merely terse: with
 * the defaults, v0.11.0 -- the release that added the entire `node:test` suite -- rendered as a
 * heading with nothing under it, and v0.7.0, which added both skills and the mode pair, showed one
 * line. Documentation is a first-class change here; the `hangar-internals` reference files are the
 * regression record for the two thirds of this CLI no test covers.
 */
import { readFileSync } from 'node:fs';

import createPreset from 'conventional-changelog-conventionalcommits';

type ChangelogType = { type: string; section?: string; hidden?: boolean };
type Plugin = string | [string, Record<string, unknown>];

const NOTES_PLUGIN = '@semantic-release/release-notes-generator';

const releaserc = JSON.parse(
  readFileSync(new URL('../.releaserc.json', import.meta.url), 'utf8'),
) as { plugins: Plugin[] };

const notes = releaserc.plugins.find(
  (plugin): plugin is [string, Record<string, unknown>] =>
    Array.isArray(plugin) && plugin[0] === NOTES_PLUGIN,
);

const types = (notes?.[1]['presetConfig'] as { types?: ChangelogType[] } | undefined)?.types;

if (types === undefined) {
  throw new Error(
    `.releaserc.json has no ${NOTES_PLUGIN} presetConfig.types to render sections from`,
  );
}

export default createPreset({ types });
