import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { CliError } from './exec.ts';
import type { Clone } from './fleet.ts';
import { themeName } from './generate/theme-json.ts';
import { envShared, fleetRoot, tildify } from './paths.ts';
import { PORT_ROLES } from './ports.ts';

/**
 * The per-clone files that are NOT in git and must be recreated whenever a clone is created
 * or re-cloned. Every one of them is derived from the clone's index, so `add-clone` writes
 * them and `doctor --fix` can repair them.
 *
 * CLAUDE.md's warning applies to two of these in particular: `CLAUDE.local.md` and the
 * `.git/info/exclude` line that hides it are a PAIR. A re-clone loses both, and recreating
 * only the first leaves it as untracked noise that eventually gets committed into a branch.
 */

export const envLocalPath = (clone: Clone): string => join(clone.path, '.env.local');
export const envrcPrivatePath = (clone: Clone): string => join(clone.path, '.envrc.private');
export const claudeLocalMdPath = (clone: Clone): string => join(clone.path, 'CLAUDE.local.md');
export const settingsPath = (clone: Clone): string =>
  join(clone.path, '.claude', 'settings.local.json');
export const excludePath = (clone: Clone): string => join(clone.path, '.git', 'info', 'exclude');
const workspaceName = (clone: Clone): string =>
  `dvb_gn_${String(clone.index).padStart(2, '0')}.code-workspace`;

export const workspacePath = (clone: Clone): string => join(clone.path, workspaceName(clone));

/**
 * The second copy of the workspace file, byte-identical to the first.
 *
 * VS Code only offers `*.code-workspace` files from the directory you opened, and this repo
 * is opened both at its root and at `angular/` -- so the file has to exist in both. Keep
 * them in step with `orch-util vscode sync`.
 */
export const workspaceAngularPath = (clone: Clone): string =>
  join(clone.path, 'angular', workspaceName(clone));
export const playwrightEnvLocalPath = (clone: Clone): string =>
  join(clone.path, 'tests', 'playwright-regression-tests', '.env.local');

/**
 * What `.git/info/exclude` has to hide, and why it cannot be the tracked `.gitignore`:
 *
 * - `/CLAUDE.local.md` is generated per clone and must never travel to a sibling.
 * - `/tmp` is a SYMLINK to the fleet's shared tmp. The tracked `.gitignore` says `tmp/`, and a
 *   trailing slash matches a directory only -- so without this line the symlink shows up as
 *   untracked in every clone until the tracked rule is relaxed to `tmp`.
 */
export const EXCLUDE_LINES = ['/CLAUDE.local.md', '/tmp'] as const;
export const EXCLUDE_LINE = EXCLUDE_LINES[0];
export const EXCLUDE_BLOCK = [
  '',
  `# Per-clone Claude Code identity and the shared tmp symlink (fleet: ${tildify(fleetRoot)})`,
  ...EXCLUDE_LINES,
  '',
].join('\n');

/** The lines `.git/info/exclude` is missing, so `doctor` can append only what is absent. */
export const missingExcludeLines = (exclude: string): string[] => {
  const present = new Set(exclude.split('\n').map((line) => line.trim()));
  return EXCLUDE_LINES.filter((line) => !present.has(line));
};

export const envLocalContent = (clone: Clone): string =>
  [
    '# Per-clone values ONLY. Secrets shared by every clone live one level up in',
    `# ${tildify(envShared)}, loaded by this clone's .envrc.private before this file`,
    '# (so anything set here still overrides the shared value).',
    '#',
    '# Ports must differ per clone: two clones sharing a dev server means a test run in one',
    "# silently verifies the other one's code. Check with `node dev/ports.mjs`.",
    '#',
    `# Generated by \`orch-util add-clone\` from the clone index (${clone.index}); repair a drifted`,
    '# value with `orch-util doctor --fix` rather than by hand.',
    '',
    `PROJECT_GIT_ROOT_PATH='${clone.path}'`,
    '',
    `${PORT_ROLES.ng.envKey}=${clone.ports.ng}`,
    `${PORT_ROLES.storybook.envKey}=${clone.ports.storybook}`,
    `${PORT_ROLES.playwrightReport.envKey}=${clone.ports.playwrightReport}`,
    '',
  ].join('\n');

export const envrcPrivateContent = (): string =>
  [
    '## Private direnv config for this clone -- gitignored, never committed.',
    '#',
    '# It sets no project variables of its own. Everything it used to set',
    '# (ATLASSIAN_USER_EMAIL, ATLASSIAN_API_TOKEN, JIRA_API_TOKEN, CONTEXT7_API_KEY,',
    '# PROJECT_GIT_ROOT_PATH) is set by dotenv files instead:',
    '#',
    `#   ${tildify(envShared)}  -- secrets identical in every clone (loaded below)`,
    "#   ./.env.local               -- this clone's own ports and PROJECT_GIT_ROOT_PATH",
    '#',
    '# The file is kept because it is the only gitignored, per-clone shell hook that direnv',
    '# already sources (`.envrc` is tracked and shared, so this load cannot live there).',
    '#',
    '# ABSOLUTE paths on purpose: `angular/.envrc` sources this file via',
    '# `load_and_watch_envrc_private ../`, so a relative `../.env.shared` would resolve',
    '# against `angular/` and silently miss. Do not "simplify" them to relative paths.',
    '#',
    "# Loaded here, which is BEFORE this clone's own `.env.local` -- so `.env.local`",
    '# still wins for anything set in both.',
    '',
    `dotenv_if_exists "${envSharedShellRef()}"`,
    `watch_file "${envSharedShellRef()}"`,
    '',
    '# The fleet orchestration CLI. direnv loads the nearest .envrc only, so this clone never',
    "# inherits the fleet root's PATH_add -- it has to be repeated here for `orch-util` to be",
    '# callable by name from inside the clone. Managed by `orch-util add-clone`; repair it',
    '# with `orch-util doctor --fix`.',
    `PATH_add "${fleetBinShellRef()}"`,
    '',
  ].join('\n');

/** The fleet's `bin/`, as `$HOME/...` so the file reads the same on any machine. */
const fleetBinShellRef = (): string =>
  join(fleetRoot, 'bin').replace(process.env['HOME'] ?? '~', '$HOME');

/** The literal PATH line, so `doctor` can assert on exactly what the generator writes. */
export const FLEET_BIN_PATH_LINE = (): string => `PATH_add "${fleetBinShellRef()}"`;

/** `$HOME/...` rather than a literal home path, matching the existing clones. */
const envSharedShellRef = (): string => envShared.replace(process.env['HOME'] ?? '~', '$HOME');

export const claudeLocalMdContent = (clone: Clone, siblings: readonly Clone[]): string => {
  const others = siblings.filter((c) => c.index !== clone.index);
  const siblingList =
    others.length === 0
      ? 'You currently have no sibling clones.'
      : `Your siblings are ${others.map((c) => `\`../${c.name}\``).join(', ')} (also git remotes of the
same name, for cherry-picking). Their working trees are off limits for writes.`;

  return [
    `# This clone: ${clone.name} (${clone.colour.name})`,
    '',
    `You are working in **\`${clone.name}\`**, one of the sibling clones under \`${tildify(fleetRoot)}/\`.`,
    `Announce yourself as **${clone.colour.name}** when the user needs to tell your session apart from`,
    'the others.',
    '',
    'Your colour is wired the same way as every other clone: the shared statusline script',
    '`~/.claude/dvb-clone-statusline.sh` (it derives the hue from this directory) plus the theme',
    `\`~/.claude/themes/${themeName(clone)}.json\`, both selected in this clone's untracked`,
    '`.claude/settings.local.json`. The status line shows the colour in every permission mode; the',
    'input-box border only does in Manual mode, which is expected — see the shared memory',
    '`clone-colour-identity` before "fixing" it.',
    '',
    '| | |',
    '| --- | --- |',
    `| Root | \`${clone.path}\` |`,
    `| Colour | ${clone.colour.name} |`,
    `| \`ng serve\` | ${clone.ports.ng} |`,
    `| Storybook | ${clone.ports.storybook} |`,
    `| Playwright report | ${clone.ports.playwrightReport} |`,
    '',
    "These ports are **yours alone**. They come from this clone's untracked `.env.local`; resolve",
    'them at run time with `node dev/ports.mjs` rather than typing a number. A server answering on',
    'any other port in those families belongs to a sibling — never test against it, never restart',
    'it, never kill it.',
    '',
    siblingList,
    `See \`../CLAUDE.md\` for the fleet rules; this clone's own \`CLAUDE.md\` and \`AGENTS.md\` are`,
    'authoritative for everything about the project itself.',
    '',
    'This file is local to this clone and excluded via `.git/info/exclude` — it never commits and',
    'never travels to a sibling. It is generated by `orch-util add-clone`; `orch-util doctor --fix` rewrites',
    'it if it drifts.',
    '',
  ].join('\n');
};

export const workspaceContent = (clone: Clone): string =>
  `${JSON.stringify(
    {
      settings: { 'yaml.maxItemsComputed': 25000 },
      folders: [{ name: `${clone.index}: dvb_gn`, path: clone.path }],
    },
    null,
    2,
  )}\n`;

/** The Storybook health-check permission, which embeds the clone's own port. */
export const storybookHealthCheckAllow = (clone: Clone): string =>
  `Bash(curl -s -o /dev/null -w "%{http_code}" --max-time 3 http://localhost:${clone.ports.storybook})`;

// Deliberately narrow: it must match the Storybook health check and nothing else. A looser
// pattern would also match a future dev-server curl allow, and rewriting the wrong one leaves
// a health check pointed at the template clone's port -- exactly the silent cross-clone
// verification the per-clone ports exist to prevent.
const HEALTH_CHECK_RE =
  /^Bash\(curl -s -o \/dev\/null -w "%\{http_code\}" --max-time 3 http:\/\/localhost:\d+\)$/;

export type HookEntry = { type: string; command: string; timeout?: number };
export type HookMatcher = { matcher?: string; hooks: HookEntry[] };

export type SettingsJson = {
  theme?: string;
  /** Must resolve INSIDE the clone -- Claude Code rejects a path that escapes the project root. */
  plansDirectory?: string;
  hooks?: Record<string, HookMatcher[]>;
  permissions?: { allow?: string[]; deny?: string[] };
  [key: string]: unknown;
};

/**
 * The `SessionEnd` hook that keeps the shared plan archive current.
 *
 * Claude Code will not write plans outside the project root -- it resolves `plansDirectory`
 * against the root and rejects anything that escapes it, symlinks followed -- so a clone
 * cannot write into `<fleet>/plans` however the setting is spelled. The clone writes to its
 * own `.claude/plans`, and this hook sweeps a session's plan into the shared archive the
 * moment that session ends, which is also the first moment it is safe to move: nothing can
 * rewrite it any more.
 *
 * It lives in the untracked per-clone settings, not in the repo: it names an absolute path in
 * this fleet, and a teammate with a single checkout has nothing to collect into.
 */
export const PLANS_HOOK_COMMAND = `${join(fleetRoot, 'bin', 'orch-util')} plans collect --quiet`;

const plansHook = (): HookMatcher => ({
  hooks: [{ type: 'command', command: PLANS_HOOK_COMMAND, timeout: 60 }],
});

export const hasPlansHook = (settings: SettingsJson | undefined): boolean =>
  (settings?.hooks?.['SessionEnd'] ?? []).some((matcher) =>
    matcher.hooks.some((hook) => hook.command === PLANS_HOOK_COMMAND),
  );

/**
 * Settings with the plan-collecting hook in place and no `plansDirectory` override.
 *
 * The override is removed deliberately: the repo's own tracked `.claude/settings.json` already
 * says `.claude/plans`, which is the only value that works, so a per-clone copy of it is one
 * more place to drift.
 */
export const withPlansHook = (settings: SettingsJson): SettingsJson => {
  const { plansDirectory: _dropped, ...rest } = settings;
  const hooks = { ...rest.hooks };
  const existing = (hooks['SessionEnd'] ?? []).filter(
    (matcher) => !matcher.hooks.some((hook) => hook.command === PLANS_HOOK_COMMAND),
  );
  hooks['SessionEnd'] = [...existing, plansHook()];
  return { ...rest, hooks };
};

/**
 * The clone's `.claude/settings.local.json`, built from a template clone.
 *
 * Everything except two values is byte-identical across the fleet, so the template is copied
 * wholesale -- but `theme` and the Storybook health-check allow are GENERATED. Copying the
 * health-check arm would point the new clone's check at the template clone's Storybook, and
 * a health check that passes against the wrong server is the exact failure the per-clone
 * ports exist to prevent.
 */
export const settingsContentFor = (clone: Clone, template: SettingsJson): string => {
  const settings: SettingsJson = structuredClone(template);
  settings.theme = `custom:${themeName(clone)}`;
  const allow = settings.permissions?.allow;
  if (allow) {
    const healthCheck = storybookHealthCheckAllow(clone);
    const matches = allow.reduce<number[]>(
      (acc, entry, i) => (HEALTH_CHECK_RE.test(entry) ? [...acc, i] : acc),
      [],
    );
    if (matches.length > 1) {
      throw new CliError(
        `the settings template has ${matches.length} Storybook health-check allows`,
        'Leave exactly one in the template clone, so there is no doubt which port to rewrite.',
      );
    }
    const index = matches[0];
    if (index === undefined) allow.push(healthCheck);
    else allow[index] = healthCheck;
  }
  return `${JSON.stringify(settings, null, 2)}\n`;
};

const readSettingsFile = (path: string): SettingsJson | undefined => {
  if (!existsSync(path)) return undefined;
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as SettingsJson;
  } catch {
    return undefined;
  }
};

export const readSettings = (clone: Clone): SettingsJson | undefined =>
  readSettingsFile(settingsPath(clone));

/** The repo's own tracked settings -- shared with the team, and not ours to edit from here. */
export const readTrackedSettings = (clone: Clone): SettingsJson | undefined =>
  readSettingsFile(join(clone.path, '.claude', 'settings.json'));

/**
 * Where this clone's plans actually land, and whether Claude Code will accept it.
 *
 * The local settings outrank the tracked ones. A value that resolves outside the clone is
 * REJECTED (with only a debug-level log) and plans fall back to `~/.claude/plans`, mixed in
 * with every other project on the machine -- which is what happened for a day when all three
 * clones pointed at an absolute shared path.
 */
export const effectivePlansDirectory = (
  clone: Clone,
): { readonly value: string | undefined; readonly resolved: string | undefined } => {
  const value = readSettings(clone)?.plansDirectory ?? readTrackedSettings(clone)?.plansDirectory;
  if (value === undefined) return { value: undefined, resolved: undefined };
  const resolved = resolve(clone.path, value);
  const inside = resolved === clone.path || resolved.startsWith(`${clone.path}/`);
  return { value, resolved: inside ? resolved : undefined };
};

/** Ports as they are actually written in the clone's `.env.local`, for drift detection. */
export const readEnvLocalPorts = (clone: Clone): Partial<Record<string, number>> => {
  const path = envLocalPath(clone);
  const found: Record<string, number> = {};
  if (!existsSync(path)) return found;
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const match = /^\s*([A-Z_]+)\s*=\s*'?"?(\d+)'?"?\s*$/.exec(line);
    if (match?.[1] && match[2]) found[match[1]] = Number.parseInt(match[2], 10);
  }
  return found;
};
