import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/**
 * Generated-artifact plumbing.
 *
 * `hangar colours sync` never writes blindly: it builds the full desired content, compares it
 * with what is on disk, and reports each file as written / unchanged / would-change. That
 * makes `--check` a real CI-style assertion and `--dry-run` genuinely side-effect free.
 */
export type Artifact = {
  readonly path: string;
  readonly content: string;
  readonly mode?: number;
  /** Why this file exists, shown in `colours sync` output. */
  readonly what: string;
};

export type ArtifactOutcome = 'written' | 'unchanged' | 'would-change' | 'would-create';

export const artifactHeader = (what: string): string =>
  [
    `# GENERATED by \`hangar colours sync\` (~/code/dvb_gn) -- do not edit by hand.`,
    `# ${what}`,
    `# The hues are data in src/palette.ts and everything else is derived from them;`,
    `# editing this file instead just means the next sync silently reverts you.`,
  ].join('\n');

const readIfPresent = (path: string): string | undefined => {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return undefined;
  }
};

export const applyArtifact = (artifact: Artifact, dryRun: boolean): ArtifactOutcome => {
  const existing = readIfPresent(artifact.path);
  if (existing === artifact.content) return 'unchanged';
  if (dryRun) return existing === undefined ? 'would-create' : 'would-change';
  mkdirSync(dirname(artifact.path), { recursive: true });
  writeFileSync(artifact.path, artifact.content, 'utf8');
  if (artifact.mode !== undefined) chmodSync(artifact.path, artifact.mode);
  return 'written';
};
