import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { CliError } from './exec.ts';
import type { Clone } from './fleet.ts';
import { themeName } from './generate/theme-json.ts';
import { envShared, fleetRoot, tildify } from './paths.ts';
import { PORT_ROLES } from './ports.ts';

/**
 * The per-clone files that are NOT in git and must be recreated whenever a clone is created
 * or re-cloned. Every one of them is derived from the clone's index, so `add-clone` writes
 * them and `doctor --fix` can repair them.
 *
 * CLAUDE.md's warning applies to two of these in particular: `CLAUDE.local.md` and the
 * `.git/info/exclude` line that hides it are a PAIR. A re-clone loses both, and recreating
 * only the first leaves it as untracked noise that eventually gets committed into a branch.
 */

export const envLocalPath = (clone: Clone): string => join(clone.path, '.env.local');
export const envrcPrivatePath = (clone: Clone): string => join(clone.path, '.envrc.private');
export const claudeLocalMdPath = (clone: Clone): string => join(clone.path, 'CLAUDE.local.md');
export const settingsPath = (clone: Clone): string =>
  join(clone.path, '.claude', 'settings.local.json');
export const excludePath = (clone: Clone): string => join(clone.path, '.git', 'info', 'exclude');
const workspaceName = (clone: Clone): string =>
  `dvb_gn_${String(clone.index).padStart(2, '0')}.code-workspace`;

export const workspacePath = (clone: Clone): string => join(clone.path, workspaceName(clone));

/**
 * The second copy of the workspace file, byte-identical to the first.
 *
 * VS Code only offers `*.code-workspace` files from the directory you opened, and this repo
 * is opened both at its root and at `angular/` -- so the file has to exist in both. Keep
 * them in step with `hangar ide vscode sync`.
 */
export const workspaceAngularPath = (clone: Clone): string =>
  join(clone.path, 'angular', workspaceName(clone));
export const playwrightEnvLocalPath = (clone: Clone): string =>
  join(clone.path, 'tests', 'playwright-regression-tests', '.env.local');

/**
 * What `.git/info/exclude` has to hide, and why it cannot be the tracked `.gitignore`:
 * `/CLAUDE.local.md` is generated per clone and must never travel to a sibling.
 *
 * `/tmp` used to be here too, for a `tmp` that was a symlink to the fleet's shared directory:
 * the tracked rule is `tmp/` and a trailing slash matches a directory only, so the link showed
 * up as untracked. `tmp/` is a real directory again -- only the cache entries INSIDE it are
 * links -- so the tracked rule covers it and this list is back to one line. An existing clone
 * that still carries the `/tmp` line is fine; it excludes something already ignored.
 */
export const EXCLUDE_LINES = ['/CLAUDE.local.md'] as const;
export const EXCLUDE_LINE = EXCLUDE_LINES[0];
export const EXCLUDE_BLOCK = [
  '',
  `# Per-clone Claude Code identity (fleet: ${tildify(fleetRoot)})`,
  ...EXCLUDE_LINES,
  '',
].join('\n');

/** The lines `.git/info/exclude` is missing, so `doctor` can append only what is absent. */
export const missingExcludeLines = (exclude: string): string[] => {
  const present = new Set(exclude.split('\n').map((line) => line.trim()));
  return EXCLUDE_LINES.filter((line) => !present.has(line));
};

export const envLocalContent = (clone: Clone): string =>
  [
    '# Per-clone values ONLY. Secrets shared by every clone live one level up in',
    `# ${tildify(envShared)}, loaded by this clone's .envrc.private before this file`,
    '# (so anything set here still overrides the shared value).',
    '#',
    '# Ports must differ per clone: two clones sharing a dev server means a test run in one',
    "# silently verifies the other one's code. Check with `node dev/ports.mjs`.",
    '#',
    `# Generated by \`hangar add-clone\` from the clone index (${clone.index}); repair a drifted`,
    '# value with `hangar doctor --fix` rather than by hand.',
    '',
    `PROJECT_GIT_ROOT_PATH='${clone.path}'`,
    '',
    `${PORT_ROLES.ng.envKey}=${clone.ports.ng}`,
    `${PORT_ROLES.storybook.envKey}=${clone.ports.storybook}`,
    `${PORT_ROLES.playwrightReport.envKey}=${clone.ports.playwrightReport}`,
    '',
  ].join('\n');

export const envrcPrivateContent = (): string =>
  [
    '## Private direnv config for this clone -- gitignored, never committed.',
    '#',
    '# It sets no project variables of its own. Everything it used to set',
    '# (ATLASSIAN_USER_EMAIL, ATLASSIAN_API_TOKEN, JIRA_API_TOKEN, CONTEXT7_API_KEY,',
    '# PROJECT_GIT_ROOT_PATH) is set by dotenv files instead:',
    '#',
    `#   ${tildify(envShared)}  -- secrets identical in every clone (loaded below)`,
    "#   ./.env.local               -- this clone's own ports and PROJECT_GIT_ROOT_PATH",
    '#',
    '# The file is kept because it is the only gitignored, per-clone shell hook that direnv',
    '# already sources (`.envrc` is tracked and shared, so this load cannot live there).',
    '#',
    '# ABSOLUTE paths on purpose: `angular/.envrc` sources this file via',
    '# `load_and_watch_envrc_private ../`, so a relative `../.env.shared` would resolve',
    '# against `angular/` and silently miss. Do not "simplify" them to relative paths.',
    '#',
    "# Loaded here, which is BEFORE this clone's own `.env.local` -- so `.env.local`",
    '# still wins for anything set in both.',
    '',
    `dotenv_if_exists "${envSharedShellRef()}"`,
    `watch_file "${envSharedShellRef()}"`,
    '',
    '# The fleet orchestration CLI. direnv loads the nearest .envrc only, so this clone never',
    "# inherits the fleet root's PATH_add -- it has to be repeated here for `hangar` to be",
    '# callable by name from inside the clone. Managed by `hangar add-clone`; repair it',
    '# with `hangar doctor --fix`.',
    `PATH_add "${fleetBinShellRef()}"`,
    '',
  ].join('\n');

/** The fleet's `bin/`, as `$HOME/...` so the file reads the same on any machine. */
const fleetBinShellRef = (): string =>
  join(fleetRoot, 'bin').replace(process.env['HOME'] ?? '~', '$HOME');

/** The literal PATH line, so `doctor` can assert on exactly what the generator writes. */
export const FLEET_BIN_PATH_LINE = (): string => `PATH_add "${fleetBinShellRef()}"`;

/** `$HOME/...` rather than a literal home path, matching the existing clones. */
const envSharedShellRef = (): string => envShared.replace(process.env['HOME'] ?? '~', '$HOME');

/**
 * A markdown table padded the way Prettier pads one.
 *
 * Not cosmetic: the clone's own `npm run md:check` globs `../**\/*.md` from `angular/`, and
 * `.git/info/exclude` hides this file from git, not from Prettier. An unpadded table put the
 * generated identity file into that repo's pre-existing formatting debt, where it looked like
 * the branch's doing and could not be fixed by anyone -- a clone agent that reformatted it
 * would then trip `doctor`'s content check instead.
 */
const paddedTable = (rows: readonly (readonly [string, string])[]): string[] => {
  const width = (column: 0 | 1): number =>
    rows.reduce((max, row) => Math.max(max, row[column].length), 0);
  const widths = [width(0), width(1)] as const;
  const line = (cells: readonly [string, string]): string =>
    `| ${cells[0].padEnd(widths[0])} | ${cells[1].padEnd(widths[1])} |`;
  return [
    line(['', '']),
    `| ${'-'.repeat(widths[0])} | ${'-'.repeat(widths[1])} |`,
    ...rows.map(line),
  ];
};

/**
 * The clone's identity file -- who this session is, and the handful of things that are true of
 * IT rather than of the fleet.
 *
 * A pure function of the clone, like every other per-clone artifact -- in particular it does NOT
 * enumerate the siblings. It used to, and `doctor`'s content check would then have turned every
 * `add-clone` and `remove-clone` into a fleet-wide red report until someone re-ran `--fix`: a
 * check that is red in normal operation is a check nobody reads.
 *
 * The fleet's own `CLAUDE.md` is already in this session's context (Claude Code walks every
 * ancestor directory), so nothing here repeats a fleet rule. What it adds is second-person:
 * text that arrives in this session unbidden, a shared directory inside this checkout, and the
 * commands that would sync the very tree the reader is editing.
 */
export const claudeLocalMdContent = (clone: Clone): string => {
  return [
    `# This clone: ${clone.name} (${clone.colour.name})`,
    '',
    `You are working in **\`${clone.name}\`**, one of the sibling clones under \`${tildify(fleetRoot)}/\`.`,
    `Announce yourself as **${clone.colour.name}** when the user needs to tell your session apart from`,
    'the others.',
    '',
    'Your colour is wired the same way as every other clone: the shared statusline script',
    '`~/.claude/dvb-clone-statusline.sh` (it derives the hue from this directory) plus the theme',
    `\`~/.claude/themes/${themeName(clone)}.json\`, both selected in this clone's untracked`,
    '`.claude/settings.local.json`. The status line shows the colour in every permission mode; the',
    'input-box border only does in Manual mode, which is expected — see the shared memory',
    '`clone-colour-identity` before "fixing" it.',
    '',
    ...paddedTable([
      ['Root', `\`${clone.path}\``],
      ['Colour', clone.colour.name],
      ['`ng serve`', String(clone.ports.ng)],
      ['Storybook', String(clone.ports.storybook)],
      ['Playwright report', String(clone.ports.playwrightReport)],
    ]),
    '',
    "These ports are **yours alone**. They come from this clone's untracked `.env.local`; resolve",
    'them at run time with `node dev/ports.mjs` rather than typing a number. A server answering on',
    'any other port in those families belongs to a sibling — never test against it, never restart',
    'it, never kill it.',
    '',
    'Your siblings are the other `clone_NN/` directories beside this one, each also a git remote of',
    'that same name for cherry-picking (`hangar list`, or `git remote`). Their working trees are',
    'off limits for writes. Which clones exist is deliberately not written down anywhere, this file',
    'included — the fleet adds and removes them without bookkeeping.',
    '',
    `See \`../CLAUDE.md\` for the fleet rules; this clone's own \`CLAUDE.md\` and \`AGENTS.md\` are`,
    'authoritative for everything about the project itself.',
    '',
    '## If a `SYNC PAUSE` line appears in your input',
    '',
    'The user can sync this clone while you are working, and `hangar sync` has no way to message',
    'a running session except to type into its terminal. So two lines may arrive that the user did',
    'not write: `SYNC PAUSE`, then exactly one `SYNC FINISHED` or `SYNC ABORTED` saying what state',
    'the working tree was left in. On a pause, stop, say that you have paused, and wait — while it',
    'runs, a separate headless Claude Code run may be resolving conflicts in this very tree, and two',
    'agents editing one file is the failure the pause exists to prevent.',
    '',
    'Stopping is always safe, so treat the pause as genuine. Resuming is not: if the closing line',
    'never comes, or describes a tree that does not match what you find, or a `SYNC FINISHED` shows',
    'up with no pause before it, tell the user rather than picking up where you left off.',
    '',
    '## `tmp/` is shared with the whole fleet',
    '',
    `Every \`tmp/<name>\` entry is a symlink into \`${tildify(fleetRoot)}/tmp/\`, and each cached Jira`,
    'record is normally a **hard link** to one file the whole fleet shares — so editing',
    "`tmp/ABC-1234/ticket_ABC-1234.md` in place may rewrite every clone's copy of it, and you cannot",
    'tell from inside the clone (a re-sync detaches that one file until the next `tmp merge`). Read',
    'those files and regenerate them with the skill; never hand-edit one. The links are not damage,',
    'so leave them alone. Dev-server PID files are the exception: they are real files, they stay in',
    'this clone, and they are why `tmp/` itself is never a symlink.',
    '',
    '## `hangar` is on your PATH — read with it, do not sync with it',
    '',
    'Reading is free and often the right move: `hangar list`, `hangar ports`, and',
    '`hangar status <N>` to see what a sibling is up to before you read its tree.',
    '',
    `But \`hangar sync ${String(clone.index)}\` — this clone — starts with a`,
    '`git stash push --include-untracked` of the tree you are working in, and the busy-clone skip',
    'applies only to `--all`, so naming a clone explicitly does not protect it. It would then type',
    'the pause message above into this very session. `merge-default` and `rebase-default` are that',
    'same command under another name, so they do all of it too. `checkout-default` would switch',
    'this working tree to the default branch and sends no pause message at all — the only thing',
    'standing in front of it is a question put to whoever is at the terminal. `open` does that',
    'same checkout before it opens a tab, so it is not only a window either. Those and',
    "`remove-clone` are the user's to run, from the fleet root.",
    '',
    'This file is local to this clone, generated by `hangar`, and excluded via',
    '`.git/info/exclude` — it never commits and never travels to a sibling. Do not hand-edit it:',
    '`hangar doctor --fix` rewrites it whenever it differs from what the generator produces. For',
    "the same reason, nothing fleet-specific belongs in this clone's tracked `.claude/` — that",
    'directory ships to every other contributor, who has one checkout and no fleet.',
    '',
  ].join('\n');
};

export const workspaceContent = (clone: Clone): string =>
  `${JSON.stringify(
    {
      settings: { 'yaml.maxItemsComputed': 25000 },
      folders: [{ name: `${clone.index}: dvb_gn`, path: clone.path }],
    },
    null,
    2,
  )}\n`;

/** The Storybook health-check permission, which embeds the clone's own port. */
export const storybookHealthCheckAllow = (clone: Clone): string =>
  `Bash(curl -s -o /dev/null -w "%{http_code}" --max-time 3 http://localhost:${clone.ports.storybook})`;

// Deliberately narrow: it must match the Storybook health check and nothing else. A looser
// pattern would also match a future dev-server curl allow, and rewriting the wrong one leaves
// a health check pointed at the template clone's port -- exactly the silent cross-clone
// verification the per-clone ports exist to prevent.
const HEALTH_CHECK_RE =
  /^Bash\(curl -s -o \/dev\/null -w "%\{http_code\}" --max-time 3 http:\/\/localhost:\d+\)$/;

export type HookEntry = { type: string; command: string; timeout?: number };
export type HookMatcher = { matcher?: string; hooks: HookEntry[] };

export type SettingsJson = {
  theme?: string;
  /** Must resolve INSIDE the clone -- Claude Code rejects a path that escapes the project root. */
  plansDirectory?: string;
  hooks?: Record<string, HookMatcher[]>;
  permissions?: { allow?: string[]; deny?: string[] };
  [key: string]: unknown;
};

/**
 * The `SessionEnd` hook that keeps the shared plan archive current.
 *
 * Claude Code will not write plans outside the project root -- it resolves `plansDirectory`
 * against the root and rejects anything that escapes it, symlinks followed -- so a clone
 * cannot write into `<fleet>/plans` however the setting is spelled. The clone writes to its
 * own `.claude/plans`, and this hook sweeps a session's plan into the shared archive the
 * moment that session ends, which is also the first moment it is safe to move: nothing can
 * rewrite it any more.
 *
 * It lives in the untracked per-clone settings, not in the repo: it names an absolute path in
 * this fleet, and a teammate with a single checkout has nothing to collect into.
 */
/**
 * Does this hook command invoke THIS hangar's CLI with this subcommand, whatever the binary was
 * called at the time it was written?
 *
 * The distinction matters exactly once per rename, and it is invisible when it goes wrong. The
 * `with*Hook` writers replace by filtering the existing matchers, so a filter keyed on the
 * CURRENT command string leaves a matcher naming yesterday's binary untouched and appends a
 * second one beside it. Every clone then carries a dead hook -- and the Jira one is designed to
 * fail open, so it would never say a word about the path not existing.
 *
 * Matching on the hangar's own `bin/` directory plus the subcommand is what survives a rename:
 * `bin/orch-util jira hook` and `bin/hangar jira hook` are both recognised as ours, while
 * another hangar's identically-named binary is not (different directory) and a different
 * subcommand is not either.
 *
 * The `has*Hook` readers deliberately do NOT use this: they answer "is the hook `doctor` would
 * write already in place", so a stale one has to read as a PROBLEM rather than as fine.
 */
const HANGAR_BIN_DIR = join(fleetRoot, 'bin');

const invokesOurCli = (command: string | undefined, subcommand: string): boolean =>
  command !== undefined && command.startsWith(`${HANGAR_BIN_DIR}/`) && command.includes(subcommand);

export const PLANS_HOOK_COMMAND = `${join(fleetRoot, 'bin', 'hangar')} plans collect --quiet`;

const plansHook = (): HookMatcher => ({
  hooks: [{ type: 'command', command: PLANS_HOOK_COMMAND, timeout: 60 }],
});

export const hasPlansHook = (settings: SettingsJson | undefined): boolean =>
  (settings?.hooks?.['SessionEnd'] ?? []).some((matcher) =>
    matcher.hooks.some((hook) => hook.command === PLANS_HOOK_COMMAND),
  );

/**
 * The `PreToolUse` hook that serves a Jira ticket from the shared record store.
 *
 * Untracked for the same reason as the plan collector, and a stronger one: the clones' `.claude`
 * is shared with every other contributor and has to work without this fleet, so nothing about
 * the record store can be in a tracked file. The matcher is `Bash` because that is how the
 * skill's sync script is invoked; the hook itself decides whether the command is one it knows,
 * and fails open on everything else.
 *
 * Additive, not a replacement: Claude Code merges the tracked settings' hooks with these, so
 * the repo's own `PreToolUse` guard still runs.
 */
export const JIRA_HOOK_COMMAND = `${join(fleetRoot, 'bin', 'hangar')} jira hook`;

const jiraHookMatcher = (): HookMatcher => ({
  matcher: 'Bash',
  hooks: [{ type: 'command', command: JIRA_HOOK_COMMAND, timeout: 30 }],
});

export const hasJiraHook = (settings: SettingsJson | undefined): boolean =>
  (settings?.hooks?.['PreToolUse'] ?? []).some((matcher) =>
    matcher.hooks.some((hook) => hook.command === JIRA_HOOK_COMMAND),
  );

export const withJiraHook = (settings: SettingsJson): SettingsJson => {
  const hooks = { ...settings.hooks };
  const existing = (hooks['PreToolUse'] ?? []).filter(
    (matcher) => !matcher.hooks.some((hook) => invokesOurCli(hook.command, 'jira hook')),
  );
  hooks['PreToolUse'] = [...existing, jiraHookMatcher()];
  return { ...settings, hooks };
};

/**
 * The `SessionEnd` hook that folds this clone's new Jira cache entries into the shared store.
 *
 * A re-sync of a ticket that already has a `tmp/<KEY>` directory writes straight into the
 * store -- that path is a symlink -- so what this catches is the two cases that need a move: a
 * brand-new ticket directory, created inside the clone by `dirFor`'s `mkdirSync`, and a record
 * whose inode a `writeAtomic` re-sync detached from the store copy.
 *
 * `SessionEnd` rather than a trigger on the write itself, and that is not a compromise: the
 * store pass deliberately leaves alone any copy written in the last two minutes, because a
 * session may be mid-refresh and the pass replaces content. A hook that fired BECAUSE a ticket
 * was just written would arrive inside its own exclusion window every time and do nothing. At
 * session end nothing is mid-write, so the guard never trips.
 *
 * The cost of not having it is bounded and worth knowing: one wasted re-fetch in a sibling.
 * The store is never a wrong answer either way -- `jira hook` reads `fetched_at:` out of the
 * file and refuses to hand back anything older than the copy the clone already holds.
 */
export const TMP_HOOK_COMMAND = `${join(fleetRoot, 'bin', 'hangar')} tmp merge --quiet`;

const tmpHook = (): HookMatcher => ({
  hooks: [{ type: 'command', command: TMP_HOOK_COMMAND, timeout: 120 }],
});

export const hasTmpHook = (settings: SettingsJson | undefined): boolean =>
  (settings?.hooks?.['SessionEnd'] ?? []).some((matcher) =>
    matcher.hooks.some((hook) => hook.command === TMP_HOOK_COMMAND),
  );

export const withTmpHook = (settings: SettingsJson): SettingsJson => {
  const hooks = { ...settings.hooks };
  const existing = (hooks['SessionEnd'] ?? []).filter(
    (matcher) => !matcher.hooks.some((hook) => invokesOurCli(hook.command, 'tmp merge')),
  );
  hooks['SessionEnd'] = [...existing, tmpHook()];
  return { ...settings, hooks };
};

/**
 * Settings with the plan-collecting hook in place and no `plansDirectory` override.
 *
 * The override is removed deliberately: the repo's own tracked `.claude/settings.json` already
 * says `.claude/plans`, which is the only value that works, so a per-clone copy of it is one
 * more place to drift.
 */
export const withPlansHook = (settings: SettingsJson): SettingsJson => {
  const { plansDirectory: _dropped, ...rest } = settings;
  const hooks = { ...rest.hooks };
  const existing = (hooks['SessionEnd'] ?? []).filter(
    (matcher) => !matcher.hooks.some((hook) => invokesOurCli(hook.command, 'plans collect')),
  );
  hooks['SessionEnd'] = [...existing, plansHook()];
  return { ...rest, hooks };
};

/**
 * The clone's `.claude/settings.local.json`, built from a template clone.
 *
 * Everything except two values is byte-identical across the fleet, so the template is copied
 * wholesale -- but `theme` and the Storybook health-check allow are GENERATED. Copying the
 * health-check arm would point the new clone's check at the template clone's Storybook, and
 * a health check that passes against the wrong server is the exact failure the per-clone
 * ports exist to prevent.
 */
export const settingsContentFor = (clone: Clone, template: SettingsJson): string => {
  const settings: SettingsJson = structuredClone(template);
  settings.theme = `custom:${themeName(clone)}`;
  const allow = settings.permissions?.allow;
  if (allow) {
    const healthCheck = storybookHealthCheckAllow(clone);
    const matches = allow.reduce<number[]>(
      (acc, entry, i) => (HEALTH_CHECK_RE.test(entry) ? [...acc, i] : acc),
      [],
    );
    if (matches.length > 1) {
      throw new CliError(
        `the settings template has ${matches.length} Storybook health-check allows`,
        'Leave exactly one in the template clone, so there is no doubt which port to rewrite.',
      );
    }
    const index = matches[0];
    if (index === undefined) allow.push(healthCheck);
    else allow[index] = healthCheck;
  }
  return `${JSON.stringify(settings, null, 2)}\n`;
};

const readSettingsFile = (path: string): SettingsJson | undefined => {
  if (!existsSync(path)) return undefined;
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as SettingsJson;
  } catch {
    return undefined;
  }
};

export const readSettings = (clone: Clone): SettingsJson | undefined =>
  readSettingsFile(settingsPath(clone));

/** The repo's own tracked settings -- shared with the team, and not ours to edit from here. */
export const readTrackedSettings = (clone: Clone): SettingsJson | undefined =>
  readSettingsFile(join(clone.path, '.claude', 'settings.json'));

/**
 * Where this clone's plans actually land, and whether Claude Code will accept it.
 *
 * The local settings outrank the tracked ones. A value that resolves outside the clone is
 * REJECTED (with only a debug-level log) and plans fall back to `~/.claude/plans`, mixed in
 * with every other project on the machine -- which is what happened for a day when all three
 * clones pointed at an absolute shared path.
 */
export const effectivePlansDirectory = (
  clone: Clone,
): { readonly value: string | undefined; readonly resolved: string | undefined } => {
  const value = readSettings(clone)?.plansDirectory ?? readTrackedSettings(clone)?.plansDirectory;
  if (value === undefined) return { value: undefined, resolved: undefined };
  const resolved = resolve(clone.path, value);
  const inside = resolved === clone.path || resolved.startsWith(`${clone.path}/`);
  return { value, resolved: inside ? resolved : undefined };
};

/** Ports as they are actually written in the clone's `.env.local`, for drift detection. */
export const readEnvLocalPorts = (clone: Clone): Partial<Record<string, number>> => {
  const path = envLocalPath(clone);
  const found: Record<string, number> = {};
  if (!existsSync(path)) return found;
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const match = /^\s*([A-Z_]+)\s*=\s*'?"?(\d+)'?"?\s*$/.exec(line);
    if (match?.[1] && match[2]) found[match[1]] = Number.parseInt(match[2], 10);
  }
  return found;
};
