import { join } from 'node:path';

/**
 * The files a hangar generates into its OWN root, as pure builders.
 *
 * `clone-config.ts` holds the per-clone equivalents and this is the hangar-level half, split out
 * for one reason: these were **tracked, with `/Users/someone` in them.**
 *
 * That is not a tidy-up. A tracked file naming one machine's home directory is a merge conflict on
 * every `git pull` from a published upstream, and worse than that on a colleague's machine the
 * paths simply do not exist -- `autoMemoryDirectory` points at nothing and the status line's
 * command is not there. **Claude Code fails both silently**: no error, no log, the badge just
 * never appears. Which is exactly the failure this hangar could never observe, because here the
 * paths happen to be right.
 *
 * So they are generated and gitignored, written by `setup`, and byte-compared by `doctor` like
 * every other generated artifact. The convention that keeps them from rotting is the same one
 * `claudeLocalMdContent` follows: ONE builder renders it, and `doctor` holds the file to that
 * render, so improving the text is one edit plus `doctor --fix`.
 */

/**
 * Takes the ROOT and the memory path, not a `Hangar`.
 *
 * `setup` has to render this file before any hangar exists -- writing the config is what makes
 * one -- so a builder demanding a `Hangar` could only be satisfied by casting a half-built object
 * into the type. Naming the two values it actually uses is both honest and what lets `setup` and
 * `doctor` call the same builder.
 */
export const hangarSettingsPath = (root: string): string => join(root, '.claude', 'settings.json');

/**
 * The hangar root's own `.claude/settings.json`.
 *
 * Three keys, and each is here for a reason that does not apply to a clone:
 *
 * - **`plansDirectory: 'plans'`**, relative and staying relative. Claude Code requires the value
 *   to resolve INSIDE the project root and silently falls back to `~/.claude/plans` otherwise --
 *   which is why the clones cannot share the archive by setting and need `hangar plans collect`
 *   instead. A fleet-root session's project root IS the hangar root, so it writes straight into
 *   the archive and needs no hook.
 * - **`autoMemoryDirectory`**, absolute, because file-based memory is keyed to the git repository
 *   root and the clones are separate repos. Without one shared path a fact learned in a clone is
 *   invisible in the other three and in the fleet-root session.
 * - **`statusLine`**, which badges the window with the hangar-root MODE it was launched in (a red
 *   `NO MODE` when it was launched in neither). `bin/hangar-mode` resolves the hangar from its own
 *   location, so only this path needs generating.
 *
 * No `permissions` block: the two `.claude/modes/*.settings.json` files carry those, and operator
 * mode's list is its security boundary -- see `hangar-internals/reference/modes.md` for why that
 * one must not be generated by a command operator mode is allowed to run.
 */
export const hangarSettingsContent = (root: string, memoryDir: string): string =>
  `${JSON.stringify(
    {
      autoMemoryDirectory: memoryDir,
      plansDirectory: 'plans',
      statusLine: {
        type: 'command',
        command: join(root, '.claude', 'modes', 'statusline.sh'),
      },
    },
    null,
    2,
  )}\n`;
