import { join } from 'node:path';

import type { Hangar } from './hangar.ts';

/**
 * The files a hangar generates into its OWN root, as pure builders.
 *
 * `clone-config.ts` holds the per-clone equivalents and this is the hangar-level half, split out
 * for one reason: these were **tracked, with `/Users/someone` in them.**
 *
 * That is not a tidy-up. A tracked file naming one machine's home directory is a merge conflict on
 * every `git pull` from a published upstream, and worse than that on a colleague's machine the
 * paths simply do not exist -- `autoMemoryDirectory` points at nothing and the status line's
 * command is not there. **Claude Code fails both silently**: no error, no log, the badge just
 * never appears. Which is exactly the failure this hangar could never observe, because here the
 * paths happen to be right.
 *
 * So they are generated and gitignored, written by `setup`, and byte-compared by `doctor` like
 * every other generated artifact. The convention that keeps them from rotting is the same one
 * `claudeLocalMdContent` follows: ONE builder renders it, and `doctor` holds the file to that
 * render, so improving the text is one edit plus `doctor --fix`.
 */

/**
 * Takes the ROOT and the memory path, not a `Hangar`.
 *
 * `setup` has to render this file before any hangar exists -- writing the config is what makes
 * one -- so a builder demanding a `Hangar` could only be satisfied by casting a half-built object
 * into the type. Naming the two values it actually uses is both honest and what lets `setup` and
 * `doctor` call the same builder.
 */
export const hangarSettingsPath = (root: string): string => join(root, '.claude', 'settings.json');

/**
 * The hangar root's own `.claude/settings.json`.
 *
 * Three keys, and each is here for a reason that does not apply to a clone:
 *
 * - **`plansDirectory: 'plans'`**, relative and staying relative. Claude Code requires the value
 *   to resolve INSIDE the project root and silently falls back to `~/.claude/plans` otherwise --
 *   which is why the clones cannot share the archive by setting and need `hangar plans collect`
 *   instead. A fleet-root session's project root IS the hangar root, so it writes straight into
 *   the archive and needs no hook.
 * - **`autoMemoryDirectory`**, absolute, because file-based memory is keyed to the git repository
 *   root and the clones are separate repos. Without one shared path a fact learned in a clone is
 *   invisible in the other three and in the fleet-root session.
 * - **`statusLine`**, which badges the window with the hangar-root MODE it was launched in (a red
 *   `NO MODE` when it was launched in neither). `bin/hangar-mode` resolves the hangar from its own
 *   location, so only this path needs generating.
 *
 * No `permissions` block: the two `.claude/modes/*.settings.json` files carry those, and operator
 * mode's list is its security boundary -- see `hangar-internals/reference/modes.md` for why that
 * one must not be generated by a command operator mode is allowed to run.
 */
export const hangarSettingsContent = (root: string, memoryDir: string): string =>
  `${JSON.stringify(
    {
      autoMemoryDirectory: memoryDir,
      plansDirectory: 'plans',
      statusLine: {
        type: 'command',
        command: join(root, '.claude', 'modes', 'statusline.sh'),
      },
    },
    null,
    2,
  )}\n`;

/**
 * The hangar root's own `CLAUDE.local.md` -- what is true of THIS hangar.
 *
 * The counterpart to the tracked `CLAUDE.md` beside it, and the split is what makes that file
 * publishable. Claude Code loads `CLAUDE.md` then `CLAUDE.local.md` from every ancestor
 * directory, so both halves reach every clone session exactly as the one file used to -- which
 * means **the split has to SHRINK the total, not move it.** Every line here is paid for once per
 * clone session, and so is every line over there.
 *
 * The division is therefore not "generic prose here, specific prose there". It is:
 *
 * - `CLAUDE.md` says **how a hangar works** -- the prohibitions, the `SYNC PAUSE` protocol, why
 *   `tmp/` is shared per entry, which commands belong to the user. Every word of it is true of
 *   every hangar, so it is tracked and published.
 * - This file says **which hangar this is** -- the root, the repo, the ports, the naming. All of
 *   it derived from `hangar.config.yaml`, none of it prose.
 *
 * A third category got DROPPED rather than relocated, and that is where the shrink came from:
 * migration history (`angular/.envrc.private no longer exists`, `clone_03 now has them too`), the
 * nine secret variable names (they are in the secrets file, which `setup` now writes), and the
 * worked Jira cache filenames. None of it was generic, and none of it was derivable.
 *
 * Takes the hangar and NOTHING ELSE -- deliberately, and for the reason `claudeLocalMdContent`
 * records about its own scope: an earlier per-clone version listed the siblings by name, which
 * would have made `doctor` red on every surviving clone after each `add-clone` until someone ran
 * `--fix`. Which clones exist stays underived from any file, this one included. That is also why
 * the ports appear as a FORMULA and a role table rather than a per-clone grid: `hangar ports` is
 * the answer to "what is clone 3 serving on", and a table here would be a second one that goes
 * stale.
 */
export const hangarClaudeLocalMdPath = (root: string): string => join(root, 'CLAUDE.local.md');

const row = (label: string, value: string): string => `| ${label.padEnd(20)} | ${value} |`;

export const hangarClaudeLocalMdContent = (hangar: Hangar): string => {
  const cfg = hangar.config;
  const { prefix, pad } = cfg.clones;
  const example = `${prefix}${'1'.padStart(pad, '0')}`;

  const rows = [
    row('hangar root', hangar.root),
    row('hangar id', hangar.id),
    row('repo', cfg.forge.originUrl),
    row(
      'default branch',
      cfg.forge.defaultBranch ?? '_not recorded yet — the first command that needs it detects it_',
    ),
    row(
      'clone directories',
      `\`${prefix}<NN>\`, at least ${String(pad)} digits — e.g. \`${example}\``,
    ),
    row(
      'app subdirectory',
      cfg.repo.appDir === '' ? '_none — the repo builds at its root_' : `\`${cfg.repo.appDir}/\``,
    ),
    row('secrets', `\`${hangar.paths.envShared}\` (mode ${cfg.secrets.mode})`),
    row('shared plans', `\`${hangar.paths.plans}\``),
    row('shared tmp', `\`${hangar.paths.tmp}\``),
    row(
      'issue keys',
      cfg.tracker.kind === 'none'
        ? '_no tracker configured_'
        : (cfg.tracker.keyPrefixes ?? []).length === 0
          ? 'any key-shaped token, minus a denylist'
          : (cfg.tracker.keyPrefixes ?? []).map((p) => `\`${p}-…\``).join(', '),
    ),
  ];

  /*
   * The port formula and the role table, not a per-clone grid.
   *
   * `offset` is in the formula even when it is 0, because a reader comparing two hangars needs to
   * see WHY their ports cannot collide -- the residue class is the whole guarantee, and a formula
   * that omitted the zero would read as if there were nothing to it.
   */
  const ports =
    cfg.ports.roles.length === 0
      ? 'This hangar assigns no ports. Nothing per-clone depends on one.\n'
      : `Every clone's ports are a pure function of its index:

    port = base + ${String(cfg.ports.offset)} + (index - 1) * ${String(cfg.ports.step)}

| role | env var | base | URL |
| ---- | ------- | ---- | --- |
${cfg.ports.roles
  .map(
    (r) =>
      `| ${r.label} | \`${r.envKey}\` | ${String(r.base)} | ${r.url === null ? '_none_' : `\`${r.url}\``} |`,
  )
  .join('\n')}

The offset is this hangar's residue class mod ${String(cfg.ports.step)}, and that is the whole
guarantee: two hangars with different offsets can never collide for any clone counts, unlike a
reserved block, which fails silently once a hangar outgrows it. **Never hard-code a port and never
assume a server on a default port is yours** — \`hangar ports\` is the answer for the fleet, and
each clone's own \`CLAUDE.local.md\` names its own.
`;

  const extras: string[] = [];
  if (cfg.repo.symlinks.length > 0) {
    extras.push(
      `## Symlinks every clone carries\n\nTargets are shown AS DECLARED: \`{secretsFile}\`, \`{index2}\` and the rest are rendered per clone.\n\n${cfg.repo.symlinks
        .map((link) => `- \`${link.path}\` → \`${link.target}\` — ${link.why}`)
        .join('\n')}\n`,
    );
  }
  if (Object.keys(cfg.repo.cloneEnv.vars).length > 0) {
    extras.push(
      `## Per-clone variables beyond the ports\n\nIn every clone's \`${cfg.repo.cloneEnv.file}\`, rendered from its index:\n\n${Object.entries(
        cfg.repo.cloneEnv.vars,
      )
        .map(([key, value]) => `- \`${key}=${value}\``)
        .join('\n')}\n`,
    );
  }

  return `<!-- GENERATED by \`hangar setup\` and \`hangar doctor --fix\` — do not edit by hand. -->

# This hangar

\`CLAUDE.md\` beside this file says how a hangar works and is the same in every one. This file says
which hangar this is, and every value in it comes from \`hangar.config.yaml\`.

| | |
| -------------------- | --- |
${rows.join('\n')}

**Which clones exist is in no file, this one included.** They are whatever \`${prefix}<NN>\`
directories are there; index gaps are normal, because \`hangar remove-clone\` never renumbers —
renumbering would move another clone's ports out from under a running server. \`hangar list\` is
the only answer, and \`git -C ${example} branch --show-current\` the only answer about a branch.

## Ports

${ports}${extras.length === 0 ? '' : `\n${extras.join('\n')}`}`;
};
