# GENERATED by `hangar colours sync` (~/code/dvb_gn) -- do not edit by hand.
# Per-clone terminal colour for the dvb_gn hangar. Source from ~/.zshrc or ~/.bashrc.
# The hues are data in src/palette.ts and everything else is derived from them;
# editing this file instead just means the next sync silently reverts you.
#
# Safe to source anywhere: a no-op in a non-interactive shell, and in any terminal whose
# escape sequences it does not know. The hue table it needs is clone-colours.sh beside it.
#
# Layers: tab/background colour where the terminal supports it, the window title, and the
# HANGAR_CLONE* variables -- which need no terminal support at all, so a prompt or a tmux
# status line can colour itself even where the chrome cannot be touched.

_hangar_dvb_gn_root='/Users/someone/code/dvb_gn'
_hangar_dvb_gn_id='dvb_gn'
_hangar_dvb_gn_tint=16   # per cent of the hue that reaches the background
_hangar_dvb_gn_chrome=1
_hangar_dvb_gn_title=1
_hangar_dvb_gn_env=1

# Interactive shells only: escape sequences in a script's output are corruption, not colour.
case $- in
    *i*) ;;
    *) return 0 ;;
esac

[ -r "${_hangar_dvb_gn_root}/clone-colours.sh" ] || return 0
. "${_hangar_dvb_gn_root}/clone-colours.sh"

# ---------------------------------------------------------------------------
# Which family of escape sequences this terminal speaks. Decided ONCE: an emulator
# cannot change under a running shell, and a subshell per `cd` is not worth it.
#
#   iterm2  OSC 6, which colours the tab in the tab bar -- the full hue.
#   konsole OSC 11 background, plus OSC 30 for the tab label.
#   osc11   OSC 11 background. VTE (GNOME Terminal), xterm, alacritty, kitty, foot, …
#   title   title only. Terminal.app ignores OSC 11, and `hangar open` paints its tabs
#           over AppleScript instead; under tmux, escape sequences would need DCS
#           passthrough and tmux has its own pane colours, so the chrome is left alone.
#   none    nothing recognised. No escape sequences at all; the env layer still works.
# ---------------------------------------------------------------------------
if [ -n "${TMUX:-}" ]; then
    _hangar_dvb_gn_fam='title'
elif [ -n "${ITERM_SESSION_ID:-}" ] || [ "${TERM_PROGRAM:-}" = 'iTerm.app' ] || [ "${LC_TERMINAL:-}" = 'iTerm2' ]; then
    _hangar_dvb_gn_fam='iterm2'
elif [ "${TERM_PROGRAM:-}" = 'Apple_Terminal' ]; then
    _hangar_dvb_gn_fam='title'
elif [ -n "${KONSOLE_VERSION:-}" ] || [ -n "${KONSOLE_DBUS_SESSION:-}" ]; then
    _hangar_dvb_gn_fam='konsole'
elif [ -n "${VTE_VERSION:-}" ] || [ -n "${GNOME_TERMINAL_SCREEN:-}" ]; then
    _hangar_dvb_gn_fam='osc11'
else
    # Two tests, not one on the two joined: TERM_PROGRAM=vscode with TERM=xterm-256color is
    # a terminal that does understand OSC 11, and a concatenated pattern would miss it.
    case "${TERM_PROGRAM:-}" in
        WezTerm|ghostty|vscode|Hyper|Tabby) _hangar_dvb_gn_fam='osc11' ;;
        *)
            case "${TERM:-}" in
                xterm*|alacritty*|foot*|rio*|contour*|kitty*|st-*) _hangar_dvb_gn_fam='osc11' ;;
                *) _hangar_dvb_gn_fam='none' ;;
            esac
            ;;
    esac
fi

# `main x tint`, as #rrggbb. The hue arrives as the r;g;b triple the table stores.
_hangar_dvb_gn_tinted() {
    local r rest g b
    r=${1%%;*}; rest=${1#*;}; g=${rest%%;*}; b=${rest#*;}
    printf '#%02x%02x%02x' "$((r * _hangar_dvb_gn_tint / 100))" "$((g * _hangar_dvb_gn_tint / 100))" "$((b * _hangar_dvb_gn_tint / 100))"
}

# $1 = r;g;b, or empty to restore the terminal default.
_hangar_dvb_gn_chrome_set() {
    [ "${_hangar_dvb_gn_chrome}" = 1 ] || return 0
    case "${_hangar_dvb_gn_fam}" in
        iterm2)
            if [ -z "$1" ]; then
                printf '\033]6;1;bg;*;default\a'
                return 0
            fi
            local r rest g b
            r=${1%%;*}; rest=${1#*;}; g=${rest%%;*}; b=${rest#*;}
            printf '\033]6;1;bg;red;brightness;%d\a'   "$r"
            printf '\033]6;1;bg;green;brightness;%d\a' "$g"
            printf '\033]6;1;bg;blue;brightness;%d\a'  "$b"
            ;;
        konsole|osc11)
            if [ -z "$1" ]; then
                # OSC 111 resets the background where it is understood (xterm, VTE). A
                # terminal that ignores it would keep the tint, so HANGAR_TERM_BG is the
                # escape hatch: set it in your rc to the background you actually use.
                if [ -n "${HANGAR_TERM_BG:-}" ]; then
                    printf '\033]11;%s\a' "$HANGAR_TERM_BG"
                else
                    printf '\033]111\a'
                fi
                return 0
            fi
            printf '\033]11;%s\a' "$(_hangar_dvb_gn_tinted "$1")"
            ;;
    esac
}

# $1 = title, or empty for "just the directory" -- the neutral a prompt framework would set.
_hangar_dvb_gn_title_set() {
    [ "${_hangar_dvb_gn_title}" = 1 ] || return 0
    # Nothing at all into a terminal we did not recognise. OSC 0 is as old and as widely
    # understood as escape sequences get, but "widely" is not "always" -- TERM=dumb, a
    # pipe, a CI log -- and a stray escape there is corruption in someone's output.
    [ "${_hangar_dvb_gn_fam}" = 'none' ] && return 0
    local text=${1:-${PWD##*/}}
    printf '\033]0;%s\a' "$text"
    [ "${_hangar_dvb_gn_fam}" = 'konsole' ] && printf '\033]30;%s\a' "$text"
    return 0
}

# The variables anything in the shell can colour itself from, with no terminal support.
_hangar_dvb_gn_env_set() {
    [ "${_hangar_dvb_gn_env}" = 1 ] || return 0
    if [ -z "$1" ]; then
        unset HANGAR_CLONE HANGAR_CLONE_COLOUR HANGAR_CLONE_RGB HANGAR_CLONE_HEX
        unset HANGAR_CLONE_X256 HANGAR_CLONE_SGR HANGAR_ID
        return 0
    fi
    export HANGAR_CLONE="$1"
    export HANGAR_CLONE_RGB="$2"
    export HANGAR_CLONE_X256="$3"
    export HANGAR_CLONE_COLOUR="$4"
    export HANGAR_ID="${_hangar_dvb_gn_id}"
    local r rest g b
    r=${2%%;*}; rest=${2#*;}; g=${rest%%;*}; b=${rest#*;}
    export HANGAR_CLONE_HEX="$(printf '#%02x%02x%02x' "$r" "$g" "$b")"
    # 24-bit where the terminal says it can, the 256-colour cube otherwise -- Terminal.app
    # is the one that matters, and it does not do true colour.
    # A real ESC, not the four characters \033: this is meant to be used directly in a
    # prompt (PS1/PROMPT), where a literal backslash-zero-three-three would print as text.
    case "${COLORTERM:-}" in
        truecolor|24bit) HANGAR_CLONE_SGR=$(printf '\033[38;2;%sm' "$2") ;;
        *) HANGAR_CLONE_SGR=$(printf '\033[38;5;%sm' "$3") ;;
    esac
    export HANGAR_CLONE_SGR
}

# ---------------------------------------------------------------------------
# The hook itself. Which clone (if any) is $PWD in, and paint accordingly.
#
# The reset is guarded so this hook only clears what IT set. Two hangars can be sourced
# into one shell; leaving A's clone for B's runs both hooks in registration order, and
# without the guard whichever ran second would undo the other. A clone the sibling hook
# has already claimed is left entirely alone -- it repaints the chrome itself.
# ---------------------------------------------------------------------------
_hangar_dvb_gn_chpwd() {
    local clone= rest= first= fields= rgb= x256= name=
    case "$PWD" in
        "${_hangar_dvb_gn_root}"/*)
            rest=${PWD#"${_hangar_dvb_gn_root}/"}
            first=${rest%%/*}
            fields=$(hangar_dvb_gn_colour "$first" 2>/dev/null) && clone=$first
            ;;
    esac

    if [ -n "$clone" ]; then
        # Split the table's three space-separated fields WITHOUT `set --`: zsh does not
        # word-split an unquoted parameter, so `set -- $fields` would hand over one field
        # there and two empty ones. Parameter expansion behaves the same in both shells.
        rgb=${fields%% *}; rest=${fields#* }; x256=${rest%% *}; name=${rest#* }
        _hangar_dvb_gn_chrome_set "$rgb"
        _hangar_dvb_gn_title_set "$clone · ${_hangar_dvb_gn_id}"
        _hangar_dvb_gn_env_set "$clone" "$rgb" "$x256" "$name"
        _hangar_dvb_gn_active=$clone
    elif [ -n "${_hangar_dvb_gn_active:-}" ]; then
        if [ -z "${HANGAR_CLONE:-}" ] || [ "${HANGAR_CLONE}" = "${_hangar_dvb_gn_active}" ]; then
            _hangar_dvb_gn_chrome_set ''
            _hangar_dvb_gn_title_set ''
            _hangar_dvb_gn_env_set ''
        fi
        unset _hangar_dvb_gn_active
    fi
}

# Fires on every prompt in bash, so skip the escape sequences unless $PWD actually moved.
_hangar_dvb_gn_maybe() {
    [ "$PWD" = "${_hangar_dvb_gn_pwd:-}" ] && return 0
    _hangar_dvb_gn_pwd=$PWD
    _hangar_dvb_gn_chpwd
    # Never leak a status: in bash this runs from PROMPT_COMMAND, where a non-zero return
    # can end up displayed as the last command's exit code by the prompt itself.
    return 0
}

if [ -n "${ZSH_VERSION:-}" ]; then
    autoload -Uz add-zsh-hook
    add-zsh-hook chpwd _hangar_dvb_gn_maybe
elif [ -n "${BASH_VERSION:-}" ]; then
    case "${PROMPT_COMMAND:-}" in
        *_hangar_dvb_gn_maybe*) ;;
        '') PROMPT_COMMAND="_hangar_dvb_gn_maybe" ;;
        *) PROMPT_COMMAND="_hangar_dvb_gn_maybe;${PROMPT_COMMAND}" ;;
    esac
fi

# Apply to the directory the shell starts in.
_hangar_dvb_gn_maybe
