#!/bin/sh
# GENERATED by `hangar colours sync` (%HANGAR%) -- do not edit by hand.
# one field of the clone status bar: clone-tmux-status.sh <footer|ticket|pr> <clone> [path]
# Called by the `#()` jobs in clone-tmux.conf, once per field per status refresh.
# Every failure is a silent exit 0: a status bar is no place for an error message.

set -u

ROOT='%HANGAR%'
PR_DIR='%HANGAR%/.hangar/pr'
KEY_PATTERN='^(BE)-[0-9]+'
DEFAULT_BRANCH='trunk'
BRANCH_MAX=72
PATH_MAX=36

field=${1:-}
clone=${2:-}
pane_path=${3:-}

# No clone means the session carries no @hangar_clone -- one somebody made by hand on this
# socket. It is on the same bar, and it is not a clone, so there is nothing to say about it.
[ -n "$field" ] || exit 0
[ -n "$clone" ] || exit 0
dir="$ROOT/$clone"
[ -d "$dir" ] || exit 0

# `symbolic-ref` and not `branch --show-current`: one ref read rather than a branch walk,
# and it exits non-zero on a detached HEAD, which is the answer "no branch" anyway. The
# footer asks git for its own branch, since one `status -b` answers that and three more.
branch=$(git -C "$dir" symbolic-ref --quiet --short HEAD 2>/dev/null) || branch=""

case "$field" in
footer)
  # Where in the clone this pane is standing. tmux knows the path and hands it over, so
  # nothing here has to guess -- and a pane that has wandered outside the clone says so
  # rather than pretending, because a footer naming the wrong tree is worse than a long one.
  rel=""
  case "$pane_path" in
  "$dir") ;;
  "$dir"/*) rel=${pane_path#"$dir"/} ;;
  "$HOME"/*) rel="~/${pane_path#"$HOME"/}" ;;
  ?*) rel=$pane_path ;;
  esac
  # From the END: the leaf directory is what says where you are, and the segments in front
  # of it are the ones the clone name has already implied.
  if [ ${#rel} -gt "$PATH_MAX" ]; then
    rel="…$(printf '%s' "$rel" | cut -c$((${#rel} - PATH_MAX + 2))-)"
  fi

  # One walk for the branch, the ahead/behind counts and every file state. See the header
  # for why --no-optional-locks is load-bearing rather than tidy.
  staged="" modified="" untracked="" conflict="" ahead="" behind="" head=""
  status=$(git -C "$dir" --no-optional-locks status --porcelain=v1 -b 2>/dev/null) || status=""
  # A here-document, not a pipe: a `while read` on the right of a pipe runs in a subshell in
  # every POSIX shell, and each variable set below would be discarded at the `done`.
  while IFS= read -r line; do
    case "$line" in
    "## "*)
      head=${line#"## "}
      head=${head%%...*}
      case "$line" in *'[ahead '*) n=${line#*'[ahead '}; n=${n%%,*}; ahead=${n%%]*} ;; esac
      case "$line" in *'behind '*) n=${line#*'behind '}; behind=${n%%]*} ;; esac
      ;;
    "??"*) untracked=1 ;;
    # A `U` on either side, and the two both-added/both-deleted spellings that carry none.
    U?*|?U*|AA*|DD*) conflict=1 ;;
    # A leading space is an empty index column: changed in the tree and not staged.
    " "*) modified=1 ;;
    ?*)
      staged=1
      case "$line" in ?M*|?D*) modified=1 ;; esac
      ;;
    esac
  done <<EOF
$status
EOF

  # A branch called `something_behind_x` would otherwise be read as a count. Both counts come
  # from the same line as the branch name, so both are checked rather than trusted.
  case "$ahead" in "" | *[!0-9]*) ahead="" ;; esac
  case "$behind" in "" | *[!0-9]*) behind="" ;; esac

  # A rebase or a merge is the state worth interrupting a glance for, so it leads.
  git_dir=$(git -C "$dir" rev-parse --git-dir 2>/dev/null) || git_dir=""
  marks=""
  if [ -n "$git_dir" ]; then
    case "$git_dir" in /*) ;; *) git_dir="$dir/$git_dir" ;; esac
    if [ -d "$git_dir/rebase-merge" ] || [ -d "$git_dir/rebase-apply" ] ||
      [ -f "$git_dir/MERGE_HEAD" ]; then
      marks="${marks}⚑"
    fi
  fi
  [ -n "$conflict" ] && marks="${marks}‼"
  [ -n "$staged" ] && marks="${marks}✚"
  [ -n "$modified" ] && marks="${marks}✱"
  [ -n "$untracked" ] && marks="${marks}?"
  # Nothing to say IS the thing to say. An empty run of glyphs would read as a broken
  # script rather than as a clean tree, so a clean tree gets a character of its own -- and
  # it is decided BEFORE the arrows, because a tree that is clean and merely ahead of its
  # remote is clean, and a lone `⇡6` there reads as an answer with the first half missing.
  [ -n "$marks" ] || marks='✔'
  [ -n "$ahead" ] && marks="${marks}⇡${ahead}"
  [ -n "$behind" ] && marks="${marks}⇣${behind}"

  # `status -b` names the branch too, and answers on a detached HEAD where `symbolic-ref`
  # cannot -- there it prints `HEAD (no branch)`, which is the honest thing to show.
  [ -n "$branch" ] || branch=$head
  if [ ${#branch} -gt "$BRANCH_MAX" ]; then
    branch="$(printf '%s' "$branch" | cut -c1-"$BRANCH_MAX")…"
  fi

  out=" $clone"
  [ -n "$rel" ] && out="$out · $rel"
  out="$out · $marks"
  [ -n "$branch" ] && out="$out · $branch"
  printf '%s ' "$out"
  ;;
ticket)
  [ -n "$branch" ] || exit 0
  [ -n "$KEY_PATTERN" ] || exit 0
  # `tr` first, so the match runs on words: `_` and `/` are separators in a branch name but
  # word characters to grep, and `-` has to survive because it is inside the key.
  key=$(printf '%s' "$branch" | tr -cs 'A-Za-z0-9-' '\n' | grep -oE "$KEY_PATTERN" |
    head -1) || key=""
  [ -n "$key" ] || exit 0
  printf ' %s ' "$key"
  ;;
pr)
  [ -n "$branch" ] || exit 0
  # Nothing to say about the default branch: it has no pull request of its own, and a link
  # to "the pull requests for master" is a link to everything.
  [ "$branch" != "$DEFAULT_BRANCH" ] || exit 0
  # The number comes off disk because asking Bitbucket for it costs a token and up to eight
  # seconds -- see `pr-cache.ts`. A cache line for another branch is not this branch's pull
  # request, so it is ignored rather than shown: that is what keying it on the branch is for.
  if [ -f "$PR_DIR/$clone" ] &&
    read -r cached_branch cached_id _rest <"$PR_DIR/$clone" &&
    [ "$cached_branch" = "$branch" ] && [ -n "$cached_id" ]; then
    printf ' PR#%s ' "$cached_id"
  else
    # A label rather than a claim: the click opens this branch's pull requests, which is a
    # true statement whether or not one exists. Without it a cold cache would leave nothing
    # on the bar to click, and the number only ever arrives by someone asking once.
    printf ' PR '
  fi
  ;;
esac
