# GENERATED by `hangar colours sync` (%HANGAR%) -- do not edit by hand.
# Canonical per-clone hues for the wt hangar. Sourceable by sh/bash/zsh.
# The hues are data in src/palette.ts and everything else is derived from them;
# editing this file instead just means the next sync silently reverts you.
#
# hangar_wt_colour <clone_NN>  ->  "<r;g;b> <xterm-256 index> <name>"
#
# Read it with two lines, in any POSIX shell:
#     set -- $(hangar_wt_colour "$clone") ; rgb=$1 x256=$2 name=$3
#
# One other place cannot source this file and carries its own copy of the table:
#   ~/.claude/wt-clone-statusline.sh
#     (self-contained on purpose: it runs on every status-line render and must never fail)
# It is generated from the same data, so the two cannot drift.
#
# Formula, so the set reads as one family: shimmer = main + 40% toward white,
# border = main x 0.8, statusline dim = main x 0.6.

hangar_wt_colour() {
    case "$1" in
        wt-001) printf '0;204;255 45 cyan'    ;;   # #00ccff
        wt-002) printf '255;204;0 220 yellow' ;;   # #ffcc00
        wt-003) printf '0;204;0 40 green'     ;;   # #00cc00
        *)      return 1 ;;
    esac
}
