#!/usr/bin/env bash
# GENERATED by `hangar colours sync` (~/code/dvb_gn) -- do not edit by hand.
# Status line for the wt hangar's clones (%HANGAR%/wt-[0-9][0-9][0-9]*).
# The hues are data in src/palette.ts and everything else is derived from them;
# editing this file instead just means the next sync silently reverts you.
#
# ONE script for all clones: the colour is derived from the clone directory in the stdin
# payload, never from an argument, so every clone runs identical code and only the hue
# differs. Hues match ~/.claude/themes/dvb-clone-*.json exactly, because both are
# generated from src/palette.ts.
set -uo pipefail

JQ="$(command -v jq || true)"
[ -n "$JQ" ] || JQ=/opt/homebrew/bin/jq

input="$(cat)"
field() { printf '%s' "$input" | "$JQ" -r "$1 // empty" 2>/dev/null; }

dir="$(field '.workspace.current_dir')"
[ -n "$dir" ] || dir="$PWD"

# The clone is the path segment under the fleet root, not basename($dir) --
# a session started in clone_01/angular/ must still report clone_01. Two or more
# digits, so this keeps working past clone_09.
FLEET='%HANGAR%'
clone="$(printf '%s' "$dir" | sed -n "s|^${FLEET}/\(wt-[0-9][0-9][0-9]*\).*|\1|p")"
[ -n "$clone" ] || clone="$(basename "$dir")"

# Same triples as the theme files: main / dim.
case "$clone" in
    wt-001) main="0;204;255"; dim="0;122;153" ;;   # cyan
    wt-002) main="255;204;0"; dim="153;122;0" ;;   # yellow
    wt-003) main="0;204;0";   dim="0;122;0"   ;;   # green
    *)      main="150;150;150"; dim="100;100;100" ;;
esac

c()  { printf '\033[38;2;%sm' "$main"; }
d()  { printf '\033[38;2;%sm' "$dim"; }
r()  { printf '\033[0m'; }

model="$(field '.model.display_name')"
branch="$(git -C "$dir" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"

out="$(c)$(printf '\033[1m')● ${clone}$(r)"
[ -n "$branch" ] && out="${out}$(d) · $(r)$(c)${branch}$(r)"
[ -n "$model" ]  && out="${out}$(d) · ${model}$(r)"
printf '%s' "$out"
